//设置AXIOS显示加载中
export const UPDATE_AXIOS_LOADING = 'UPDATE_AXIOS_LOADING'
//设置错误时候提示的模态框类型
export const UPDATE_AXIOS_ALARM_TYPE = 'UPDATE_AXIOS_ALARM_TYPE'
//设置默认值
export const UPDATE_AXIOS_DEFAULT = 'UPDATE_AXIOS_DEFAULT'
